version: '3'
services:
  spring_boot_realworld_example_app:
    image: 0b4cb87a081e
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: "com.mysql.jdbc.Driver"
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    ports: 
      - "8080:8080"
    depends_on: 
      - db

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports: 
      - "3306:3306"



